"use strict";

window.WORLD_HERITAGES = [
  { number: 98, name: "法隆寺", wikipedia: "法隆寺" },
  { number: 72, name: "屋久島", wikipedia: "屋久島" },
  { number: 38, name: "ヴェルサイユ宮殿", wikipedia: "ヴェルサイユ宮殿" },
  { number: 48, name: "軍艦島", wikipedia: "端島 (長崎県)" },
  { number: 42, name: "ピサの斜塔", wikipedia: "ピサの斜塔" },
  { number: 78, name: "バーミヤン渓谷の文化的景観と古代遺跡群", wikipedia: "バーミヤン渓谷の文化的景観と古代遺跡群" },
  { number: 34, name: "モスクワのクレムリンと赤の広場", wikipedia: "赤の広場" },
  { number: 325, name: "独立記念館", wikipedia: "独立記念館 (アメリカ)" },
  { number: 147, name: "シルクロード：長安＝天山回廊の交易路網", wikipedia: "シルクロード:長安-天山回廊の交易路網" },
  { number: 103, name: "ラパ・ヌイ国立公園（モアイ）", wikipedia: "ラパ・ヌイ国立公園" },
  { number: 14, name: "コロッセオ", wikipedia: "コロッセオ" },
  { number: 2, name: "ケルン大聖堂", wikipedia: "ケルン大聖堂" },
  { number: 7, name: "サグラダ・ファミリア", wikipedia: "サグラダ・ファミリア" },
  { number: 10, name: "パリのセーヌ河岸", wikipedia: "パリのセーヌ河岸" },
  { number: 77, name: "富士山", wikipedia: "富士山" },
  { number: 24, name: "マチュ・ピチュ", wikipedia: "マチュ・ピチュ" },
  { number: 15, name: "グランド・キャニオン国立公園", wikipedia: "グランド・キャニオン国立公園" },
  { number: 96, name: "清水寺", wikipedia: "清水寺" },
  { number: 4, name: "自由の女神", wikipedia: "自由の女神像 (ニューヨーク)" },
  { number: 185, name: "姫路城", wikipedia: "姫路城" },
  { number: 3, name: "イエローストーン国立公園", wikipedia: "イエローストーン国立公園" },
  { number: 9, name: "アルベロベッロのトゥルッリ", wikipedia: "アルベロベッロ" },
  { number: 617, name: "アルダブラ環礁", wikipedia: "アルダブラ環礁" },
  { number: 8, name: "モン・サン・ミッシェルとその湾", wikipedia: "モン・サン＝ミシェル" },
  { number: 421, name: "白川郷", wikipedia: "白川郷・五箇山の合掌造り集落" },
  { number: 63, name: "厳島神社", wikipedia: "厳島神社" },
  { number: 23, name: "イグアスの滝", wikipedia: "イグアスの滝" },
  { number: 224, name: "ンゴロンゴロ自然保護区", wikipedia: "ンゴロンゴロ保全地域" },
  { number: 243, name: "知床", wikipedia: "知床 (世界遺産)" },
  { number: 25, name: "メンフィスのピラミッド地帯", wikipedia: "メンフィスとその墓地遺跡" },
  { number: 384, name: "白神山地", wikipedia: "白神山地" },
];
